declare module "@sentry/nextjs" {
  export const captureException: (...args: unknown[]) => string;
  export const init: (...args: unknown[]) => void;
}

declare module "lucide-react" {
  import type { ComponentType, SVGProps } from "react";

  export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const BarChart3: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Bot: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronLeftIcon: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Circle: LucideIcon;
  export const Clock3: LucideIcon;
  export const Copy: LucideIcon;
  export const CreditCard: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Download: LucideIcon;
  export const Eye: LucideIcon;
  export const FileSpreadsheet: LucideIcon;
  export const Github: LucideIcon;
  export const Globe: LucideIcon;
  export const GripVertical: LucideIcon;
  export const Headphones: LucideIcon;
  export const Inbox: LucideIcon;
  export const Info: LucideIcon;
  export const KeyRound: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const LifeBuoy: LucideIcon;
  export const Linkedin: LucideIcon;
  export const ListChecks: LucideIcon;
  export const Loader2: LucideIcon;
  export const LogIn: LucideIcon;
  export const Megaphone: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const MessageSquarePlus: LucideIcon;
  export const MessagesSquare: LucideIcon;
  export const Minus: LucideIcon;
  export const Monitor: LucideIcon;
  export const Moon: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const PanelLeft: LucideIcon;
  export const Paperclip: LucideIcon;
  export const Pencil: LucideIcon;
  export const Play: LucideIcon;
  export const Plug: LucideIcon;
  export const Plus: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Save: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Server: LucideIcon;
  export const Shield: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const ShieldOff: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Sun: LucideIcon;
  export const Table2: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Twitter: LucideIcon;
  export const Upload: LucideIcon;
  export const User: LucideIcon;
  export const UserMinus: LucideIcon;
  export const UserRound: LucideIcon;
  export const Users: LucideIcon;
  export const Wand2: LucideIcon;
  export const Wifi: LucideIcon;
  export const WifiOff: LucideIcon;
  export const Workflow: LucideIcon;
  export const Wrench: LucideIcon;
  export const X: LucideIcon;
  export const Youtube: LucideIcon;
  export const Zap: LucideIcon;
}
