/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125PricingRouteImport } from './routes/{-$locale}/pricing'
import { Route as Char123LocaleChar125ImprintRouteImport } from './routes/{-$locale}/imprint'
import { Route as Char123LocaleChar125FaqRouteImport } from './routes/{-$locale}/faq'
import { Route as Char123LocaleChar125DocsRouteImport } from './routes/{-$locale}/docs'
import { Route as AuthenticatedWhatsNewRouteImport } from './routes/_authenticated/whats-new'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInstancesRouteImport } from './routes/_authenticated/instances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as Char123LocaleChar125DocsIndexRouteImport } from './routes/{-$locale}/docs.index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog.index'
import { Route as Char123LocaleChar125DocsToolsRouteImport } from './routes/{-$locale}/docs.tools'
import { Route as Char123LocaleChar125DocsSecurityRouteImport } from './routes/{-$locale}/docs.security'
import { Route as Char123LocaleChar125DocsQuotasRouteImport } from './routes/{-$locale}/docs.quotas'
import { Route as Char123LocaleChar125DocsN8nInstancesRouteImport } from './routes/{-$locale}/docs.n8n-instances'
import { Route as Char123LocaleChar125DocsGettingStartedRouteImport } from './routes/{-$locale}/docs.getting-started'
import { Route as Char123LocaleChar125DocsConceptsRouteImport } from './routes/{-$locale}/docs.concepts'
import { Route as Char123LocaleChar125DocsClientsRouteImport } from './routes/{-$locale}/docs.clients'
import { Route as Char123LocaleChar125DocsApiKeysRouteImport } from './routes/{-$locale}/docs.api-keys'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}/blog.$slug'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle-webhook'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminTicketsRouteImport } from './routes/_authenticated/_admin/admin.tickets'
import { Route as AuthenticatedAdminAdminIntegrationsRouteImport } from './routes/_authenticated/_admin/admin.integrations'
import { Route as AuthenticatedAdminAdminDeploymentRouteImport } from './routes/_authenticated/_admin/admin.deployment'
import { Route as AuthenticatedAdminAdminDeletionRequestsRouteImport } from './routes/_authenticated/_admin/admin.deletion-requests'
import { Route as AuthenticatedAdminAdminAnnouncementsRouteImport } from './routes/_authenticated/_admin/admin.announcements'
import { Route as AuthenticatedAdminAdminAnnouncementsPreviewIdRouteImport } from './routes/_authenticated/_admin/admin.announcements.preview.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/{-$locale}/terms',
    path: '/{-$locale}/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/{-$locale}/privacy',
    path: '/{-$locale}/privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PricingRoute =
  Char123LocaleChar125PricingRouteImport.update({
    id: '/{-$locale}/pricing',
    path: '/{-$locale}/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ImprintRoute =
  Char123LocaleChar125ImprintRouteImport.update({
    id: '/{-$locale}/imprint',
    path: '/{-$locale}/imprint',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125FaqRoute = Char123LocaleChar125FaqRouteImport.update({
  id: '/{-$locale}/faq',
  path: '/{-$locale}/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125DocsRoute =
  Char123LocaleChar125DocsRouteImport.update({
    id: '/{-$locale}/docs',
    path: '/{-$locale}/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWhatsNewRoute = AuthenticatedWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstancesRoute = AuthenticatedInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char123LocaleChar125DocsIndexRoute =
  Char123LocaleChar125DocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/{-$locale}/blog/',
    path: '/{-$locale}/blog/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DocsToolsRoute =
  Char123LocaleChar125DocsToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsSecurityRoute =
  Char123LocaleChar125DocsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsQuotasRoute =
  Char123LocaleChar125DocsQuotasRouteImport.update({
    id: '/quotas',
    path: '/quotas',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsN8nInstancesRoute =
  Char123LocaleChar125DocsN8nInstancesRouteImport.update({
    id: '/n8n-instances',
    path: '/n8n-instances',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsGettingStartedRoute =
  Char123LocaleChar125DocsGettingStartedRouteImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsConceptsRoute =
  Char123LocaleChar125DocsConceptsRouteImport.update({
    id: '/concepts',
    path: '/concepts',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsClientsRoute =
  Char123LocaleChar125DocsClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125DocsApiKeysRoute =
  Char123LocaleChar125DocsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/{-$locale}/blog/$slug',
    path: '/{-$locale}/blog/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminTicketsRoute =
  AuthenticatedAdminAdminTicketsRouteImport.update({
    id: '/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminIntegrationsRoute =
  AuthenticatedAdminAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDeploymentRoute =
  AuthenticatedAdminAdminDeploymentRouteImport.update({
    id: '/admin/deployment',
    path: '/admin/deployment',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDeletionRequestsRoute =
  AuthenticatedAdminAdminDeletionRequestsRouteImport.update({
    id: '/admin/deletion-requests',
    path: '/admin/deletion-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnnouncementsRoute =
  AuthenticatedAdminAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnnouncementsPreviewIdRoute =
  AuthenticatedAdminAdminAnnouncementsPreviewIdRouteImport.update({
    id: '/preview/$id',
    path: '/preview/$id',
    getParentRoute: () => AuthenticatedAdminAdminAnnouncementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAdminRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instances': typeof AuthenticatedInstancesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteWithChildren
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/imprint': typeof Char123LocaleChar125ImprintRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/docs/api-keys': typeof Char123LocaleChar125DocsApiKeysRoute
  '/{-$locale}/docs/clients': typeof Char123LocaleChar125DocsClientsRoute
  '/{-$locale}/docs/concepts': typeof Char123LocaleChar125DocsConceptsRoute
  '/{-$locale}/docs/getting-started': typeof Char123LocaleChar125DocsGettingStartedRoute
  '/{-$locale}/docs/n8n-instances': typeof Char123LocaleChar125DocsN8nInstancesRoute
  '/{-$locale}/docs/quotas': typeof Char123LocaleChar125DocsQuotasRoute
  '/{-$locale}/docs/security': typeof Char123LocaleChar125DocsSecurityRoute
  '/{-$locale}/docs/tools': typeof Char123LocaleChar125DocsToolsRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/docs/': typeof Char123LocaleChar125DocsIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  '/admin/deletion-requests': typeof AuthenticatedAdminAdminDeletionRequestsRoute
  '/admin/deployment': typeof AuthenticatedAdminAdminDeploymentRoute
  '/admin/integrations': typeof AuthenticatedAdminAdminIntegrationsRoute
  '/admin/tickets': typeof AuthenticatedAdminAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/announcements/preview/$id': typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAdminRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instances': typeof AuthenticatedInstancesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/imprint': typeof Char123LocaleChar125ImprintRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/docs/api-keys': typeof Char123LocaleChar125DocsApiKeysRoute
  '/{-$locale}/docs/clients': typeof Char123LocaleChar125DocsClientsRoute
  '/{-$locale}/docs/concepts': typeof Char123LocaleChar125DocsConceptsRoute
  '/{-$locale}/docs/getting-started': typeof Char123LocaleChar125DocsGettingStartedRoute
  '/{-$locale}/docs/n8n-instances': typeof Char123LocaleChar125DocsN8nInstancesRoute
  '/{-$locale}/docs/quotas': typeof Char123LocaleChar125DocsQuotasRoute
  '/{-$locale}/docs/security': typeof Char123LocaleChar125DocsSecurityRoute
  '/{-$locale}/docs/tools': typeof Char123LocaleChar125DocsToolsRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  '/admin/deletion-requests': typeof AuthenticatedAdminAdminDeletionRequestsRoute
  '/admin/deployment': typeof AuthenticatedAdminAdminDeploymentRoute
  '/admin/integrations': typeof AuthenticatedAdminAdminIntegrationsRoute
  '/admin/tickets': typeof AuthenticatedAdminAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/announcements/preview/$id': typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/instances': typeof AuthenticatedInstancesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/whats-new': typeof AuthenticatedWhatsNewRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteWithChildren
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/imprint': typeof Char123LocaleChar125ImprintRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/docs/api-keys': typeof Char123LocaleChar125DocsApiKeysRoute
  '/{-$locale}/docs/clients': typeof Char123LocaleChar125DocsClientsRoute
  '/{-$locale}/docs/concepts': typeof Char123LocaleChar125DocsConceptsRoute
  '/{-$locale}/docs/getting-started': typeof Char123LocaleChar125DocsGettingStartedRoute
  '/{-$locale}/docs/n8n-instances': typeof Char123LocaleChar125DocsN8nInstancesRoute
  '/{-$locale}/docs/quotas': typeof Char123LocaleChar125DocsQuotasRoute
  '/{-$locale}/docs/security': typeof Char123LocaleChar125DocsSecurityRoute
  '/{-$locale}/docs/tools': typeof Char123LocaleChar125DocsToolsRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/docs/': typeof Char123LocaleChar125DocsIndexRoute
  '/_authenticated/_admin/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  '/_authenticated/_admin/admin/deletion-requests': typeof AuthenticatedAdminAdminDeletionRequestsRoute
  '/_authenticated/_admin/admin/deployment': typeof AuthenticatedAdminAdminDeploymentRoute
  '/_authenticated/_admin/admin/integrations': typeof AuthenticatedAdminAdminIntegrationsRoute
  '/_authenticated/_admin/admin/tickets': typeof AuthenticatedAdminAdminTicketsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/announcements/preview/$id': typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api-keys'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/dashboard'
    | '/instances'
    | '/settings'
    | '/tickets'
    | '/usage'
    | '/whats-new'
    | '/{-$locale}/docs'
    | '/{-$locale}/faq'
    | '/{-$locale}/imprint'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/api/public/mcp'
    | '/api/public/paddle-webhook'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/docs/api-keys'
    | '/{-$locale}/docs/clients'
    | '/{-$locale}/docs/concepts'
    | '/{-$locale}/docs/getting-started'
    | '/{-$locale}/docs/n8n-instances'
    | '/{-$locale}/docs/quotas'
    | '/{-$locale}/docs/security'
    | '/{-$locale}/docs/tools'
    | '/{-$locale}/blog/'
    | '/{-$locale}/docs/'
    | '/admin/announcements'
    | '/admin/deletion-requests'
    | '/admin/deployment'
    | '/admin/integrations'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/announcements/preview/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api-keys'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/dashboard'
    | '/instances'
    | '/settings'
    | '/tickets'
    | '/usage'
    | '/whats-new'
    | '/{-$locale}/faq'
    | '/{-$locale}/imprint'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/api/public/mcp'
    | '/api/public/paddle-webhook'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/docs/api-keys'
    | '/{-$locale}/docs/clients'
    | '/{-$locale}/docs/concepts'
    | '/{-$locale}/docs/getting-started'
    | '/{-$locale}/docs/n8n-instances'
    | '/{-$locale}/docs/quotas'
    | '/{-$locale}/docs/security'
    | '/{-$locale}/docs/tools'
    | '/{-$locale}/blog'
    | '/{-$locale}/docs'
    | '/admin/announcements'
    | '/admin/deletion-requests'
    | '/admin/deployment'
    | '/admin/integrations'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/announcements/preview/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin-setup'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/_admin'
    | '/_authenticated/api-keys'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/connect'
    | '/_authenticated/dashboard'
    | '/_authenticated/instances'
    | '/_authenticated/settings'
    | '/_authenticated/tickets'
    | '/_authenticated/usage'
    | '/_authenticated/whats-new'
    | '/{-$locale}/docs'
    | '/{-$locale}/faq'
    | '/{-$locale}/imprint'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/api/public/mcp'
    | '/api/public/paddle-webhook'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/docs/api-keys'
    | '/{-$locale}/docs/clients'
    | '/{-$locale}/docs/concepts'
    | '/{-$locale}/docs/getting-started'
    | '/{-$locale}/docs/n8n-instances'
    | '/{-$locale}/docs/quotas'
    | '/{-$locale}/docs/security'
    | '/{-$locale}/docs/tools'
    | '/{-$locale}/blog/'
    | '/{-$locale}/docs/'
    | '/_authenticated/_admin/admin/announcements'
    | '/_authenticated/_admin/admin/deletion-requests'
    | '/_authenticated/_admin/admin/deployment'
    | '/_authenticated/_admin/admin/integrations'
    | '/_authenticated/_admin/admin/tickets'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/announcements/preview/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminSetupRoute: typeof AdminSetupRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125DocsRoute: typeof Char123LocaleChar125DocsRouteWithChildren
  Char123LocaleChar125FaqRoute: typeof Char123LocaleChar125FaqRoute
  Char123LocaleChar125ImprintRoute: typeof Char123LocaleChar125ImprintRoute
  Char123LocaleChar125PricingRoute: typeof Char123LocaleChar125PricingRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/{-$locale}/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/{-$locale}/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/pricing': {
      id: '/{-$locale}/pricing'
      path: '/{-$locale}/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/imprint': {
      id: '/{-$locale}/imprint'
      path: '/{-$locale}/imprint'
      fullPath: '/{-$locale}/imprint'
      preLoaderRoute: typeof Char123LocaleChar125ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/faq': {
      id: '/{-$locale}/faq'
      path: '/{-$locale}/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof Char123LocaleChar125FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs': {
      id: '/{-$locale}/docs'
      path: '/{-$locale}/docs'
      fullPath: '/{-$locale}/docs'
      preLoaderRoute: typeof Char123LocaleChar125DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whats-new': {
      id: '/_authenticated/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof AuthenticatedWhatsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances': {
      id: '/_authenticated/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AuthenticatedInstancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/{-$locale}/docs/': {
      id: '/{-$locale}/docs/'
      path: '/'
      fullPath: '/{-$locale}/docs/'
      preLoaderRoute: typeof Char123LocaleChar125DocsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/{-$locale}/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs/tools': {
      id: '/{-$locale}/docs/tools'
      path: '/tools'
      fullPath: '/{-$locale}/docs/tools'
      preLoaderRoute: typeof Char123LocaleChar125DocsToolsRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/security': {
      id: '/{-$locale}/docs/security'
      path: '/security'
      fullPath: '/{-$locale}/docs/security'
      preLoaderRoute: typeof Char123LocaleChar125DocsSecurityRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/quotas': {
      id: '/{-$locale}/docs/quotas'
      path: '/quotas'
      fullPath: '/{-$locale}/docs/quotas'
      preLoaderRoute: typeof Char123LocaleChar125DocsQuotasRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/n8n-instances': {
      id: '/{-$locale}/docs/n8n-instances'
      path: '/n8n-instances'
      fullPath: '/{-$locale}/docs/n8n-instances'
      preLoaderRoute: typeof Char123LocaleChar125DocsN8nInstancesRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/getting-started': {
      id: '/{-$locale}/docs/getting-started'
      path: '/getting-started'
      fullPath: '/{-$locale}/docs/getting-started'
      preLoaderRoute: typeof Char123LocaleChar125DocsGettingStartedRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/concepts': {
      id: '/{-$locale}/docs/concepts'
      path: '/concepts'
      fullPath: '/{-$locale}/docs/concepts'
      preLoaderRoute: typeof Char123LocaleChar125DocsConceptsRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/clients': {
      id: '/{-$locale}/docs/clients'
      path: '/clients'
      fullPath: '/{-$locale}/docs/clients'
      preLoaderRoute: typeof Char123LocaleChar125DocsClientsRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/docs/api-keys': {
      id: '/{-$locale}/docs/api-keys'
      path: '/api-keys'
      fullPath: '/{-$locale}/docs/api-keys'
      preLoaderRoute: typeof Char123LocaleChar125DocsApiKeysRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/{-$locale}/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/tickets': {
      id: '/_authenticated/_admin/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/integrations': {
      id: '/_authenticated/_admin/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/deployment': {
      id: '/_authenticated/_admin/admin/deployment'
      path: '/admin/deployment'
      fullPath: '/admin/deployment'
      preLoaderRoute: typeof AuthenticatedAdminAdminDeploymentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/deletion-requests': {
      id: '/_authenticated/_admin/admin/deletion-requests'
      path: '/admin/deletion-requests'
      fullPath: '/admin/deletion-requests'
      preLoaderRoute: typeof AuthenticatedAdminAdminDeletionRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/announcements': {
      id: '/_authenticated/_admin/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/announcements/preview/$id': {
      id: '/_authenticated/_admin/admin/announcements/preview/$id'
      path: '/preview/$id'
      fullPath: '/admin/announcements/preview/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAnnouncementsRoute
    }
  }
}

interface AuthenticatedAdminAdminAnnouncementsRouteChildren {
  AuthenticatedAdminAdminAnnouncementsPreviewIdRoute: typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}

const AuthenticatedAdminAdminAnnouncementsRouteChildren: AuthenticatedAdminAdminAnnouncementsRouteChildren =
  {
    AuthenticatedAdminAdminAnnouncementsPreviewIdRoute:
      AuthenticatedAdminAdminAnnouncementsPreviewIdRoute,
  }

const AuthenticatedAdminAdminAnnouncementsRouteWithChildren =
  AuthenticatedAdminAdminAnnouncementsRoute._addFileChildren(
    AuthenticatedAdminAdminAnnouncementsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAnnouncementsRoute: typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  AuthenticatedAdminAdminDeletionRequestsRoute: typeof AuthenticatedAdminAdminDeletionRequestsRoute
  AuthenticatedAdminAdminDeploymentRoute: typeof AuthenticatedAdminAdminDeploymentRoute
  AuthenticatedAdminAdminIntegrationsRoute: typeof AuthenticatedAdminAdminIntegrationsRoute
  AuthenticatedAdminAdminTicketsRoute: typeof AuthenticatedAdminAdminTicketsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAnnouncementsRoute:
    AuthenticatedAdminAdminAnnouncementsRouteWithChildren,
  AuthenticatedAdminAdminDeletionRequestsRoute:
    AuthenticatedAdminAdminDeletionRequestsRoute,
  AuthenticatedAdminAdminDeploymentRoute:
    AuthenticatedAdminAdminDeploymentRoute,
  AuthenticatedAdminAdminIntegrationsRoute:
    AuthenticatedAdminAdminIntegrationsRoute,
  AuthenticatedAdminAdminTicketsRoute: AuthenticatedAdminAdminTicketsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstancesRoute: typeof AuthenticatedInstancesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedWhatsNewRoute: typeof AuthenticatedWhatsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstancesRoute: AuthenticatedInstancesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedWhatsNewRoute: AuthenticatedWhatsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface Char123LocaleChar125DocsRouteChildren {
  Char123LocaleChar125DocsApiKeysRoute: typeof Char123LocaleChar125DocsApiKeysRoute
  Char123LocaleChar125DocsClientsRoute: typeof Char123LocaleChar125DocsClientsRoute
  Char123LocaleChar125DocsConceptsRoute: typeof Char123LocaleChar125DocsConceptsRoute
  Char123LocaleChar125DocsGettingStartedRoute: typeof Char123LocaleChar125DocsGettingStartedRoute
  Char123LocaleChar125DocsN8nInstancesRoute: typeof Char123LocaleChar125DocsN8nInstancesRoute
  Char123LocaleChar125DocsQuotasRoute: typeof Char123LocaleChar125DocsQuotasRoute
  Char123LocaleChar125DocsSecurityRoute: typeof Char123LocaleChar125DocsSecurityRoute
  Char123LocaleChar125DocsToolsRoute: typeof Char123LocaleChar125DocsToolsRoute
  Char123LocaleChar125DocsIndexRoute: typeof Char123LocaleChar125DocsIndexRoute
}

const Char123LocaleChar125DocsRouteChildren: Char123LocaleChar125DocsRouteChildren =
  {
    Char123LocaleChar125DocsApiKeysRoute: Char123LocaleChar125DocsApiKeysRoute,
    Char123LocaleChar125DocsClientsRoute: Char123LocaleChar125DocsClientsRoute,
    Char123LocaleChar125DocsConceptsRoute:
      Char123LocaleChar125DocsConceptsRoute,
    Char123LocaleChar125DocsGettingStartedRoute:
      Char123LocaleChar125DocsGettingStartedRoute,
    Char123LocaleChar125DocsN8nInstancesRoute:
      Char123LocaleChar125DocsN8nInstancesRoute,
    Char123LocaleChar125DocsQuotasRoute: Char123LocaleChar125DocsQuotasRoute,
    Char123LocaleChar125DocsSecurityRoute:
      Char123LocaleChar125DocsSecurityRoute,
    Char123LocaleChar125DocsToolsRoute: Char123LocaleChar125DocsToolsRoute,
    Char123LocaleChar125DocsIndexRoute: Char123LocaleChar125DocsIndexRoute,
  }

const Char123LocaleChar125DocsRouteWithChildren =
  Char123LocaleChar125DocsRoute._addFileChildren(
    Char123LocaleChar125DocsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminSetupRoute: AdminSetupRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125DocsRoute: Char123LocaleChar125DocsRouteWithChildren,
  Char123LocaleChar125FaqRoute: Char123LocaleChar125FaqRoute,
  Char123LocaleChar125ImprintRoute: Char123LocaleChar125ImprintRoute,
  Char123LocaleChar125PricingRoute: Char123LocaleChar125PricingRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
  Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
