/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DocsToolsRouteImport } from './routes/docs.tools'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsQuotasRouteImport } from './routes/docs.quotas'
import { Route as DocsN8nInstancesRouteImport } from './routes/docs.n8n-instances'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as DocsClientsRouteImport } from './routes/docs.clients'
import { Route as DocsApiKeysRouteImport } from './routes/docs.api-keys'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedWhatsNewRouteImport } from './routes/_authenticated/whats-new'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInstancesRouteImport } from './routes/_authenticated/instances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle-webhook'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminIntegrationsRouteImport } from './routes/_authenticated/_admin/admin.integrations'
import { Route as AuthenticatedAdminAdminDeploymentRouteImport } from './routes/_authenticated/_admin/admin.deployment'
import { Route as AuthenticatedAdminAdminDeletionRequestsRouteImport } from './routes/_authenticated/_admin/admin.deletion-requests'
import { Route as AuthenticatedAdminAdminAnnouncementsRouteImport } from './routes/_authenticated/_admin/admin.announcements'
import { Route as AuthenticatedAdminAdminAnnouncementsPreviewIdRouteImport } from './routes/_authenticated/_admin/admin.announcements.preview.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsToolsRoute = DocsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuotasRoute = DocsQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => DocsRoute,
} as any)
const DocsN8nInstancesRoute = DocsN8nInstancesRouteImport.update({
  id: '/n8n-instances',
  path: '/n8n-instances',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsRoute = DocsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiKeysRoute = DocsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DocsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsNewRoute = AuthenticatedWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstancesRoute = AuthenticatedInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminIntegrationsRoute =
  AuthenticatedAdminAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDeploymentRoute =
  AuthenticatedAdminAdminDeploymentRouteImport.update({
    id: '/admin/deployment',
    path: '/admin/deployment',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDeletionRequestsRoute =
  AuthenticatedAdminAdminDeletionRequestsRouteImport.update({
    id: '/admin/deletion-requests',
    path: '/admin/deletion-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnnouncementsRoute =
  AuthenticatedAdminAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnnouncementsPreviewIdRoute =
  AuthenticatedAdminAdminAnnouncementsPreviewIdRouteImport.update({
    id: '/preview/$id',
    path: '/preview/$id',
    getParentRoute: () => AuthenticatedAdminAdminAnnouncementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instances': typeof AuthenticatedInstancesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/n8n-instances': typeof DocsN8nInstancesRoute
  '/docs/quotas': typeof DocsQuotasRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/tools': typeof DocsToolsRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  '/admin/deletion-requests': typeof AuthenticatedAdminAdminDeletionRequestsRoute
  '/admin/deployment': typeof AuthenticatedAdminAdminDeploymentRoute
  '/admin/integrations': typeof AuthenticatedAdminAdminIntegrationsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/announcements/preview/$id': typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instances': typeof AuthenticatedInstancesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/n8n-instances': typeof DocsN8nInstancesRoute
  '/docs/quotas': typeof DocsQuotasRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/tools': typeof DocsToolsRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  '/admin/deletion-requests': typeof AuthenticatedAdminAdminDeletionRequestsRoute
  '/admin/deployment': typeof AuthenticatedAdminAdminDeploymentRoute
  '/admin/integrations': typeof AuthenticatedAdminAdminIntegrationsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/announcements/preview/$id': typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/instances': typeof AuthenticatedInstancesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/whats-new': typeof AuthenticatedWhatsNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/clients': typeof DocsClientsRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/n8n-instances': typeof DocsN8nInstancesRoute
  '/docs/quotas': typeof DocsQuotasRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/tools': typeof DocsToolsRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/_authenticated/_admin/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  '/_authenticated/_admin/admin/deletion-requests': typeof AuthenticatedAdminAdminDeletionRequestsRoute
  '/_authenticated/_admin/admin/deployment': typeof AuthenticatedAdminAdminDeploymentRoute
  '/_authenticated/_admin/admin/integrations': typeof AuthenticatedAdminAdminIntegrationsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/announcements/preview/$id': typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/docs'
    | '/faq'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/api-keys'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/dashboard'
    | '/instances'
    | '/settings'
    | '/usage'
    | '/whats-new'
    | '/blog/$slug'
    | '/docs/api-keys'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/n8n-instances'
    | '/docs/quotas'
    | '/docs/security'
    | '/docs/tools'
    | '/blog/'
    | '/docs/'
    | '/api/public/mcp'
    | '/api/public/paddle-webhook'
    | '/admin/announcements'
    | '/admin/deletion-requests'
    | '/admin/deployment'
    | '/admin/integrations'
    | '/admin/users'
    | '/admin/announcements/preview/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/faq'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/api-keys'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/dashboard'
    | '/instances'
    | '/settings'
    | '/usage'
    | '/whats-new'
    | '/blog/$slug'
    | '/docs/api-keys'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/n8n-instances'
    | '/docs/quotas'
    | '/docs/security'
    | '/docs/tools'
    | '/blog'
    | '/docs'
    | '/api/public/mcp'
    | '/api/public/paddle-webhook'
    | '/admin/announcements'
    | '/admin/deletion-requests'
    | '/admin/deployment'
    | '/admin/integrations'
    | '/admin/users'
    | '/admin/announcements/preview/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-setup'
    | '/docs'
    | '/faq'
    | '/imprint'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/_admin'
    | '/_authenticated/api-keys'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/connect'
    | '/_authenticated/dashboard'
    | '/_authenticated/instances'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_authenticated/whats-new'
    | '/blog/$slug'
    | '/docs/api-keys'
    | '/docs/clients'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/n8n-instances'
    | '/docs/quotas'
    | '/docs/security'
    | '/docs/tools'
    | '/blog/'
    | '/docs/'
    | '/api/public/mcp'
    | '/api/public/paddle-webhook'
    | '/_authenticated/_admin/admin/announcements'
    | '/_authenticated/_admin/admin/deletion-requests'
    | '/_authenticated/_admin/admin/deployment'
    | '/_authenticated/_admin/admin/integrations'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/announcements/preview/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminSetupRoute: typeof AdminSetupRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ImprintRoute: typeof ImprintRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tools': {
      id: '/docs/tools'
      path: '/tools'
      fullPath: '/docs/tools'
      preLoaderRoute: typeof DocsToolsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quotas': {
      id: '/docs/quotas'
      path: '/quotas'
      fullPath: '/docs/quotas'
      preLoaderRoute: typeof DocsQuotasRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/n8n-instances': {
      id: '/docs/n8n-instances'
      path: '/n8n-instances'
      fullPath: '/docs/n8n-instances'
      preLoaderRoute: typeof DocsN8nInstancesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients': {
      id: '/docs/clients'
      path: '/clients'
      fullPath: '/docs/clients'
      preLoaderRoute: typeof DocsClientsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-keys': {
      id: '/docs/api-keys'
      path: '/api-keys'
      fullPath: '/docs/api-keys'
      preLoaderRoute: typeof DocsApiKeysRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whats-new': {
      id: '/_authenticated/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof AuthenticatedWhatsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances': {
      id: '/_authenticated/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AuthenticatedInstancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/integrations': {
      id: '/_authenticated/_admin/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/deployment': {
      id: '/_authenticated/_admin/admin/deployment'
      path: '/admin/deployment'
      fullPath: '/admin/deployment'
      preLoaderRoute: typeof AuthenticatedAdminAdminDeploymentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/deletion-requests': {
      id: '/_authenticated/_admin/admin/deletion-requests'
      path: '/admin/deletion-requests'
      fullPath: '/admin/deletion-requests'
      preLoaderRoute: typeof AuthenticatedAdminAdminDeletionRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/announcements': {
      id: '/_authenticated/_admin/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/announcements/preview/$id': {
      id: '/_authenticated/_admin/admin/announcements/preview/$id'
      path: '/preview/$id'
      fullPath: '/admin/announcements/preview/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAnnouncementsRoute
    }
  }
}

interface AuthenticatedAdminAdminAnnouncementsRouteChildren {
  AuthenticatedAdminAdminAnnouncementsPreviewIdRoute: typeof AuthenticatedAdminAdminAnnouncementsPreviewIdRoute
}

const AuthenticatedAdminAdminAnnouncementsRouteChildren: AuthenticatedAdminAdminAnnouncementsRouteChildren =
  {
    AuthenticatedAdminAdminAnnouncementsPreviewIdRoute:
      AuthenticatedAdminAdminAnnouncementsPreviewIdRoute,
  }

const AuthenticatedAdminAdminAnnouncementsRouteWithChildren =
  AuthenticatedAdminAdminAnnouncementsRoute._addFileChildren(
    AuthenticatedAdminAdminAnnouncementsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAnnouncementsRoute: typeof AuthenticatedAdminAdminAnnouncementsRouteWithChildren
  AuthenticatedAdminAdminDeletionRequestsRoute: typeof AuthenticatedAdminAdminDeletionRequestsRoute
  AuthenticatedAdminAdminDeploymentRoute: typeof AuthenticatedAdminAdminDeploymentRoute
  AuthenticatedAdminAdminIntegrationsRoute: typeof AuthenticatedAdminAdminIntegrationsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAnnouncementsRoute:
    AuthenticatedAdminAdminAnnouncementsRouteWithChildren,
  AuthenticatedAdminAdminDeletionRequestsRoute:
    AuthenticatedAdminAdminDeletionRequestsRoute,
  AuthenticatedAdminAdminDeploymentRoute:
    AuthenticatedAdminAdminDeploymentRoute,
  AuthenticatedAdminAdminIntegrationsRoute:
    AuthenticatedAdminAdminIntegrationsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstancesRoute: typeof AuthenticatedInstancesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedWhatsNewRoute: typeof AuthenticatedWhatsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstancesRoute: AuthenticatedInstancesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedWhatsNewRoute: AuthenticatedWhatsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsApiKeysRoute: typeof DocsApiKeysRoute
  DocsClientsRoute: typeof DocsClientsRoute
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsN8nInstancesRoute: typeof DocsN8nInstancesRoute
  DocsQuotasRoute: typeof DocsQuotasRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsToolsRoute: typeof DocsToolsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiKeysRoute: DocsApiKeysRoute,
  DocsClientsRoute: DocsClientsRoute,
  DocsConceptsRoute: DocsConceptsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsN8nInstancesRoute: DocsN8nInstancesRoute,
  DocsQuotasRoute: DocsQuotasRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsToolsRoute: DocsToolsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminSetupRoute: AdminSetupRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  ImprintRoute: ImprintRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
